### ISSUE TITLE
Note admonition not rendering correctly

### ISSUE THREAD

**Issue by giltho** [elviswolcott/remark-admonitions#17]
Hi !
I'm using remark-admonitions through docusaurus v2 and it seems that in the dark theme, the wrong CSS variables are being used.

Light mode: 
![image](https://user-images.githubusercontent.com/8451179/75348391-a4202780-589a-11ea-9c55-d56ceb1bb229.png)

Dark mode:
![image](https://user-images.githubusercontent.com/8451179/75348399-a8e4db80-589a-11ea-9c42-56f11685d7b0.png)

**Comment by elviswolcott** [comment]
Thanks for bringing this to my attention. I'll get a fix put together sometime later today.

**Comment by elviswolcott** [comment]
![fixed](https://user-images.githubusercontent.com/10013769/75378967-3f64cd00-589a-11ea-8275-de920906f0b0.png)

Found the culprit [/styles/infima.css#L15](https://github.com/elviswolcott/remark-admonitions/blob/master/styles/infima.css#L15)
