### ISSUE TITLE
Support admonitions within html tags

### ISSUE THREAD

**Issue by bendtherules** [elviswolcott/remark-admonitions#28]
This should be supported within markdown -

```
<details>
 <summary>hello</summary>
  :::note Extra
    Something here
  :::
</details>
```

Currently, it doesn't work.

I expect this to work, because in Docusaurus - other markdown within html tag seems to work??  
Ex -  This shows code block within details, but not admonition.
```
<details>
 <summary>hello</summary>
:::note Extra
  Hello world

```js
some code here
\```
:::
</details>
```

**Comment by elviswolcott** [comment]
I'm going to be re-writing this plugin sometime in the next few weeks for the new remark parser. If It's a trivial fix, I'll update it, but otherwise markdown inside HTML is something that isn't really intended behavior AFAIK.
